server:
  port: 8555

spring:
  application:
    name: api-gateway

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8666/eureka/
    register-with-eureka: false