server:
  port: 8666

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.5  #保护模式，代表留存得服务实例低于50%时，不会消除任何实例（包括以及没有心跳得实例）
    enable-self-preservation: true  #开启保护模式
  client:
    register-with-eureka: false    #代便是否注册eureka,表示自身可以注册，保持高可用，一般单点情况时false
    fetch-registry: false   #是否启用获取服务注册信息，注册中心（server）不需要开启
    service-url:
      #注册和查询都需要依赖该地址，多个地址得话用逗号隔开
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



wht:
  whtDemo:
    length: 10