server:
  port: 8666

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.5
    enable-self-preservation: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8666/eureka/



wht:
  whtDemo:
    length: 10