server:
  port: 8333
spring:
  application:
    name: user-service
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    #最大连接数
    maxActive: 30
    #最小连接数
    minIdle: 5
    #获取连接得最大等待时间
    maxWait: 10000
    #解决mysql8小时问题
    validationQuery: SELECT 'X'
    #空闲连接检查时间间隔
    timeBetweenEvictionRunsMillis: 60000
    #空闲连接最小空闲时间
    minEvictableIdleTimeMillis: 300000

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8666/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


